[plugin]
repository = "https://github.com/Glorou/CleanHuntChat.git"
commit = "a0363e2688333340b660efe6a4fc2805930ff605"
owners = ["Guerzoniansus", "Glorou"]
project_path = "CleanHuntChat"
changelog = "Version 1.2"
