[plugin]
repository = "https://github.com/Glorou/CleanHuntChat.git"
commit = "731bc218b835fdeed07ddc76b2b0fe803e227fa0"
owners = ["Guerzoniansus", "Glorou"]
project_path = "CleanHuntChat"
changelog = "Version 1.2: Fixed plugin unloading, added a feature to allow you to permanently enable filters for shout and yell"
